services:
  php:
    container_name: php-container
    build:
        context: ./docker/php
    ports:
        - "9000:9000"
    volumes:
        - .:/var/www/project
    depends_on:
        - postgres
    networks:
      nginx-php-database:
        aliases:
          - php-container
      
  nginx:
      container_name: nginx-container
      build:
        context: ./docker/nginx
      ports:
          - ${NGINX_PORT}:80
      volumes:
          - .:/var/www/project:ro
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      restart: always
      depends_on:
          - php
      networks:
        nginx-php-database:
          aliases:
            - nginx-container
  postgres:
    container_name: postgres-container
    build:
      context: ./docker/postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      nginx-php-database:
        aliases:
          - postgres-container

volumes:
  database_data:

networks:
  nginx-php-database:
    name: nginx-php-database